### ISSUE TITLE
Why "prettier/prettier": "error"?

### ISSUE THREAD

**Issue by PaulRBerg** [fvictorio/solhint-plugin-prettier#3]
Great plugin! Just what I was looking for to start using solhint and prettier-plugin-solidity together.

The README indicates that we should set the "prettier" rule to "error", but gives no explanation for why we should do that.

**Comment by PaulRBerg** [comment]
Wait, judging by the release dates for solhint v3, this plugin seems to be outdated and should be rewritten, no?

**Comment by fvictorio** [comment]
Ok, apparently my user automatically stopped watching this repo (as many others, wtf github??). So sorry for not answering before!

You can use "warning" instead of "error", that's just fine. Do you think it would make more sense for the readme to have that as a default?

I don't really have a strong opinion here. For me, an error is something that stops you from committing, and forgetting to run prettier seems like something you'd want to know. That's the only reason. But, again, either level seems fine to me :slightly_smiling_face:

**Comment by PaulRBerg** [comment]
No worries!

> You can use "warning" instead of "error", that's just fine. Do you think it would make more sense for the readme to have that as a default?

Perhaps? What I was alluding to is more of like explaining the rationale behind doing this.

**Comment by fvictorio** [comment]
Forgot to close this. Thanks again Paul!
